name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run tests
        run: make test
        continue-on-error: false

      - name: Build package
        if: github.ref == 'refs/heads/main'
        run: |
          hatchling build
          export VERSION=$(hatchling version | awk '{print $NF}')
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV
        continue-on-error: false

      - name: Publish distribution to PyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Add tag to repository
        if: github.ref == 'refs/heads/main' && success()
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: v${{ env.PACKAGE_VERSION }}

